name: business_card
description: A new Flutter project.
publish_to: 'none' 

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17
  
  flutter_phone_direct_caller:
    git:
      url: https://github.com/yanisalfian/flutter-phone-direct-caller.git
  cupertino_icons: ^1.0.2
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/